version: "3.2"
services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    networks:
      - arrnetwork
    ports:
      - 7878:7878
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/appdata/radarr:/config:rw
      - /mnt/user/data/:/data:rw
    labels:
      - "net.unraid.docker.icon=https://hotio.dev/webhook-avatars/radarr.png"
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.wedenig.local`)"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    networks:
      - arrnetwork
    ports:
      - 8989:8989
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/appdata/sonarr:/config:rw
      - /mnt/user/data:/data:rw
    labels:
      - "net.unraid.docker.icon=https://hotio.dev/webhook-avatars/sonarr.png"     
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.wedenig.local`)"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"  
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    networks:
      - arrnetwork
    ports:
      - 6767:6767
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/appdata/bazarr:/config:rw
      - /mnt/user/data/media:/data/media:rw
    labels:
      - "net.unraid.docker.icon=https://hotio.dev/webhook-avatars/bazarr.png"
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.wedenig.local`)"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"  
  readarr:
    container_name: readarr
    image: ghcr.io/hotio/readarr
    restart: unless-stopped
    networks:
      - arrnetwork
    logging:
      driver: json-file
    ports:
      - "8787:8787"
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/user/appdata/readarr:/config
      - /mnt/user/data:/data
    labels:
      - "net.unraid.docker.icon=https://hotio.dev/webhook-avatars/readarr.png"
      - "traefik.enable=true"
      - "traefik.http.routers.readarr.rule=Host(`readarr.wedenig.local`)"
      - "traefik.http.services.readarr.loadbalancer.server.port=8686"  
  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr
    restart: unless-stopped
    logging:
      driver: json-file
    networks:
      - arrnetwork
    ports:
      - "8686:8686"
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/user/appdata/lidarr:/config
      - /mnt/user/data:/data
    labels:
      - "net.unraid.docker.icon=https://hotio.dev/webhook-avatars/lidarr.png"
      - "traefik.enable=true"
      - "traefik.http.routers.lidarr.rule=Host(`lidarr.wedenig.local`)"
      - "traefik.http.services.lidarr.loadbalancer.server.port=8686"  
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    networks:
      - arrnetwork
    ports:
      - 9696:9696
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/user/appdata/prowlarr:/config:rw
    labels:
      - "net.unraid.docker.icon=https://hotio.dev/webhook-avatars/prowlarr.png"
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.wedenig.local`)"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"  
  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd:latest
    restart: unless-stopped
    logging:
      driver: json-file
    networks:
      - arrnetwork
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/appdata/sabnzbd:/config:rw
      - /mnt/user/data/usenet:/data/usenet:rw
    labels:
      - "net.unraid.docker.icon=https://hotio.dev/webhook-avatars/sabnzbd.png"
      - "traefik.enable=true"
      - "traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.wedenig.local`)"
      - "traefik.http.services.sabnzbd.loadbalancer.server.port=8080"  
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    networks:
      - arrnetwork
    ports:
      - "8081:8080"
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Amsterdam
      - UMASK=002
      - WEBUI_PORTS=8080/tcp,8080/udp
      - VPN_ENABLED=true 
      - VPN_CONF=nordvpn-aut132
      - VPN_PROVIDER=generic
      - VPN_LAN_NETWORK=192.168.0.0/24
      - VPN_LAN_LEAK_ENABLED=false
      - VPN_EXPOSE_PORTS_ON_LAN
      - VPN_AUTO_PORT_FORWARD=false
      - VPN_KEEP_LOCAL_DNS=false
      - VPN_FIREWALL_TYPE=auto
      - VPN_HEALTHCHECK_ENABLED=true
      - PRIVOXY_ENABLED=false
      - UNBOUND_ENABLED=false
    volumes:
      - /mnt/user/appdata/qbittorrent:/config
      - /mnt/user/data/torrents:/data/torrents
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1 #
      - net.ipv6.conf.all.disable_ipv6=1 #
    labels:
      - "net.unraid.docker.icon=https://hotio.dev/webhook-avatars/qbittorrent.png"
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`torrents.wedenig.local`)"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"  
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    logging:
      driver: json-file
    networks:
      - arrnetwork
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Amsterdam
      - PORT=5055
    ports:
      - 5055:5055
    volumes:
      - /mnt/user/appdata/config:/app/config
    labels:
      - "net.unraid.docker.icon=https://hotio.dev/webhook-avatars/overseerr.png"
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`overseerr.wedenig.local`)"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"  
    restart: unless-stopped
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    logging:
      driver: json-file
    networks:
      - arrnetwork
    volumes:
      - /mnt/user/appdata/tautulli:/config
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Amsterdam
    ports:
      - 8181:8181
    restart: unless-stopped
    labels:
      - "net.unraid.docker.icon=https://hotio.dev/webhook-avatars/tautulli.png"
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.rule=Host(`tautulli.wedenig.local`)"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"  
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    networks:
      - arrnetwork
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=Europe/Amsterdam
      - PUID=99
      - PGID=100
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=TdarrMainNode
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /mnt/user/appdata/tdarr/server:/app/server
      - /mnt/user/appdata/tdarr/configs:/app/configs
      - /mnt/user/appdata/tdarr/logs:/app/logs
      - /mnt/user/data/media:/media
      - /mnt/user/private:/private
      - /mnt/user/appdata/tdarr/transcode_cache:/temp
    labels:
      - "net.unraid.docker.icon=https://home.tdarr.io/static/media/logo3-min.246d6df44c7f16ddebaf.pngng"
      - "traefik.enable=true"
      - "traefik.http.routers.tdarr.rule=Host(`tdarr.wedenig.local`)"
      - "traefik.http.services.tdarr.loadbalancer.server.port=8265"
networks:
  arrnetwork:
    driver: bridge
    internal: false
