version: "3.2"
services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    networks:
      - arrnetwork
    ports:
      - 7878:7878
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/appdata/radarr:/config:rw
      - /mnt/user/data/:/data:rw
    labels:
     - "net.unraid.docker.icon=https://hotio.dev/webhook-avatars/radarr.png"
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    networks:
      - arrnetwork
    ports:
      - 8989:8989
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/appdata/sonarr:/config:rw
      - /mnt/user/data:/data:rw
    labels:
     - "net.unraid.docker.icon=https://hotio.dev/webhook-avatars/sonarr.png"       
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    networks:
      - arrnetwork
    ports:
      - 6767:6767
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/appdata/bazarr:/config:rw
      - /mnt/user/data/media:/data/media:rw
    labels:
     - "net.unraid.docker.icon=https://hotio.dev/webhook-avatars/bazarr.png"
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    ports:
      - 9696:9696
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/user/appdata/prowlarr:/config:rw
    labels:
     - "net.unraid.docker.icon=https://hotio.dev/webhook-avatars/prowlarr.png"
  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd:latest
    restart: unless-stopped
    logging:
      driver: json-file
    networks:
      - arrnetwork
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/appdata/sabnzbd:/config:rw
      - /mnt/user/data/usenet:/data/usenet:rw
    labels:
     - "net.unraid.docker.icon=https://hotio.dev/webhook-avatars/sabnzbd.png"
networks:
  arrnetwork:
    driver: bridge
    internal: false
