version: "3.2"
services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    networks:
      - arrnetwork
    ports:
      - 7878:7878
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/appdata/radarr:/config:rw
      - /mnt/user/data/:/data:rw
    labels:
     - "net.unraid.docker.icon=https://hotio.dev/webhook-avatars/radarr.png"
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    networks:
      - arrnetwork
    ports:
      - 8989:8989
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/appdata/sonarr:/config:rw
      - /mnt/user/data:/data:rw
    labels:
     - "net.unraid.docker.icon=https://hotio.dev/webhook-avatars/sonarr.png"       
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    networks:
      - arrnetwork
    ports:
      - 6767:6767
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/appdata/bazarr:/config:rw
      - /mnt/user/data/media:/data/media:rw
    labels:
     - "net.unraid.docker.icon=https://hotio.dev/webhook-avatars/bazarr.png"
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    networks:
      - arrnetwork
    ports:
      - 9696:9696
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/user/appdata/prowlarr:/config:rw
    labels:
     - "net.unraid.docker.icon=https://hotio.dev/webhook-avatars/prowlarr.png"
  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd:latest
    restart: unless-stopped
    logging:
      driver: json-file
    networks:
      - arrnetwork
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Amsterdam
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/appdata/sabnzbd:/config:rw
      - /mnt/user/data/usenet:/data/usenet:rw
    labels:
     - "net.unraid.docker.icon=https://hotio.dev/webhook-avatars/sabnzbd.png"
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    logging:
      driver: json-file
    networks:
      - arrnetwork
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Amsterdam
      - PORT=5055
    ports:
      - 5055:5055
    volumes:
      - /mnt/user/appdata/config:/app/config
    labels:
      - "net.unraid.docker.icon=https://hotio.dev/webhook-avatars/overseerr.png"
    restart: unless-stopped
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    logging:
      driver: json-file
    networks:
      - arrnetwork
    volumes:
      -/mnt/user/appdata/tautulli:/config
    environment:
      - PUID=99
      - PGID=100
      - TZ=Europe/Amsterdam
    ports:
      - 8181:8181
    restart: unless-stopped
    labels:
      - "net.unraid.docker.icon=https://hotio.dev/webhook-avatars/tautulli.png"
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    networks:
      - arrnetwork
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=Europe/Amsterdam
      - PUID=99
      - PGID=100
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=MyInternalNode
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /mnt/user/appdata/tdarr/server:/app/server
      - /mnt/user/appdata/tdarr/configs:/app/configs
      - /mnt/user/appdata/tdarr/logs:/app/logs
      - /mnt/user/data/media:/media
      - /mnt/user/appdata/tdarr/transcode_cache:/temp
networks:
  arrnetwork:
    driver: bridge
    internal: false
